name: Docker Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t student-management:${{ github.ref_name }} .
          docker tag student-management:${{ github.ref_name }} student-management:${{ steps.vars.outputs.sha_short }}

      - name: Save Docker Image Artifact
        run: |
          docker save student-management:${{ github.ref_name }} -o student-management.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.ref_name }}
          path: student-management.tar
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true